services:

  postgres:
    image: postgres:17
    container_name: medlab_postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # ports:
    #   - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped


  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: medlab_api

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      ENVIRONMENT: ${ENVIRONMENT}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8188:8000"

    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
      - ./reports:/app/reports

    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: medlab_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: medlab_celery_worker

    command: >
      celery
      -A app.workers.celery_app.celery_app
      worker
      --loglevel=info

    env_file:
      - .env

    depends_on:
      - postgres
      - redis
    
    volumes:
      - ./app:/app/app
      - ./reports:/app/reports

    restart: unless-stopped


volumes:
  postgres_data:
  redis_data: