# ==========================================================
# Stage 1 — Builder
# ==========================================================

FROM python:3.13-slim AS builder

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /build

COPY requirements.txt .

RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir \
       --prefix=/install \
       -r requirements.txt


# ==========================================================
# Stage 2 — Production
# ==========================================================

FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# ----------------------------------------------------------
# Usuario no-root
# ----------------------------------------------------------

RUN groupadd --system medlab \
    && useradd --system \
       --gid medlab \
       --create-home \
       medlab

# ----------------------------------------------------------
# Dependencias
# ----------------------------------------------------------

COPY --from=builder /install /usr/local

# ----------------------------------------------------------
# Aplicación
# ----------------------------------------------------------

COPY app ./app
COPY alembic ./alembic
COPY alembic.ini .

# ----------------------------------------------------------
# Reports
# ----------------------------------------------------------

RUN mkdir -p /app/reports \
    && chown -R medlab:medlab /app

USER medlab

# ----------------------------------------------------------
# Puerto
# ----------------------------------------------------------

EXPOSE 8000

# ----------------------------------------------------------
# Healthcheck
# ----------------------------------------------------------

HEALTHCHECK \
    --interval=30s \
    --timeout=5s \
    --start-period=20s \
    --retries=3 \
    CMD python -c \
    "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health/db')"


# ----------------------------------------------------------
# API
# ----------------------------------------------------------

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
