[pytest]

pythonpath = .

testpaths = tests

addopts =
    -v
    --strict-markers
    --cov=app
    --cov-report=term-missing
    --cov-report=xml
    --cov-fail-under=80

markers =
    unit: pruebas unitarias
    integration: pruebas de integración
    security: pruebas de seguridad
    celery: pruebas relacionadas con Celery