"""create laboratory domain tables

Revision ID: 75bba8f0ecaa
Revises: 004a48abcf29
Create Date: 2026-08-13 11:41:16.600669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bba8f0ecaa'
down_revision: Union[str, Sequence[str], None] = '004a48abcf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_medical_record'), 'patients', ['medical_record'], unique=True)
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_code', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_type', sa.Enum('BLOOD', 'URINE', 'SALIVA', 'TISSUE', 'OTHER', name='sample_type'), nullable=False),
    sa.Column('status', sa.Enum('COLLECTED', 'RECEIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sample_status'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_sample_code'), 'samples', ['sample_code'], unique=True)
    op.create_table('laboratory_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('result_value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'VALIDATED', 'CANCELLED', name='test_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratory_tests')
    op.drop_index(op.f('ix_samples_sample_code'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_patients_medical_record'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
