"""equipment lifecycle and maintenance

Revision ID: 7e31cdc60bb0
Revises: bd0ab5e9fe61
Create Date: 2026-09-14 01:09:25.131857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e31cdc60bb0'
down_revision: Union[str, Sequence[str], None] = 'bd0ab5e9fe61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_lifecycle_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('performed_by', sa.String(length=150), nullable=True),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['biomedical_equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_lifecycle_events_equipment_id'), 'equipment_lifecycle_events', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_lifecycle_events_event_date'), 'equipment_lifecycle_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_equipment_lifecycle_events_event_type'), 'equipment_lifecycle_events', ['event_type'], unique=False)
    op.create_table('maintenance_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('maintenance_type', sa.String(length=30), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_execution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['biomedical_equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_schedules_equipment_id'), 'maintenance_schedules', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_schedules_is_active'), 'maintenance_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_maintenance_schedules_next_due_date'), 'maintenance_schedules', ['next_due_date'], unique=False)
    op.create_table('maintenances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('maintenance_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=150), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['biomedical_equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenances_equipment_id'), 'maintenances', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenances_maintenance_type'), 'maintenances', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenances_scheduled_date'), 'maintenances', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenances_status'), 'maintenances', ['status'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maintenance_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performed_by', sa.String(length=150), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['biomedical_equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_id'), 'maintenance_records', ['maintenance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_maintenance_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_maintenances_status'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_scheduled_date'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_maintenance_type'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_equipment_id'), table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_index(op.f('ix_maintenance_schedules_next_due_date'), table_name='maintenance_schedules')
    op.drop_index(op.f('ix_maintenance_schedules_is_active'), table_name='maintenance_schedules')
    op.drop_index(op.f('ix_maintenance_schedules_equipment_id'), table_name='maintenance_schedules')
    op.drop_table('maintenance_schedules')
    op.drop_index(op.f('ix_equipment_lifecycle_events_event_type'), table_name='equipment_lifecycle_events')
    op.drop_index(op.f('ix_equipment_lifecycle_events_event_date'), table_name='equipment_lifecycle_events')
    op.drop_index(op.f('ix_equipment_lifecycle_events_equipment_id'), table_name='equipment_lifecycle_events')
    op.drop_table('equipment_lifecycle_events')
    # ### end Alembic commands ###
