"""add email to patients

Revision ID: 90d1ed8970bc
Revises: 75bba8f0ecaa
Create Date: 2026-08-13 13:15:08.144474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d1ed8970bc'
down_revision: Union[str, Sequence[str], None] = '75bba8f0ecaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###
