"""notifications

Revision ID: bd0ab5e9fe61
Revises: 67bc640e6f2c
Create Date: 2026-09-07 01:14:07.084084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd0ab5e9fe61"
down_revision: str | Sequence[str] | None = "67bc640e6f2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "CALIBRATION_EXPIRED", "CALIBRATION_EXPIRING", name="notification_type"
    ).create(op.get_bind())
    sa.Enum("VALID", "EXPIRED", name="calibration_status").create(op.get_bind())
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "CALIBRATION_EXPIRED",
                "CALIBRATION_EXPIRING",
                name="notification_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("entity_name", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("deduplication_key", sa.String(length=255), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_deduplication_key"),
        "notifications",
        ["deduplication_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.alter_column(
        "calibrations",
        "status",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum("VALID", "EXPIRED", name="calibration_status"),
        existing_nullable=False,
        postgresql_using="status::calibration_status",
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="audit_action",
        new_values=[
            "CREATE",
            "UPDATE",
            "DELETE",
            "VALIDATE",
            "LOGIN",
            "STATUS_CHANGED",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="audit_logs", column_name="action"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="audit_action",
        new_values=["CREATE", "UPDATE", "DELETE", "VALIDATE", "LOGIN"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="audit_logs", column_name="action"
            )
        ],
        enum_values_to_rename=[],
    )
    op.alter_column(
        "calibrations",
        "status",
        existing_type=sa.Enum("VALID", "EXPIRED", name="calibration_status"),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_deduplication_key"), table_name="notifications"
    )
    op.drop_table("notifications")
    sa.Enum("VALID", "EXPIRED", name="calibration_status").drop(op.get_bind())
    sa.Enum(
        "CALIBRATION_EXPIRED", "CALIBRATION_EXPIRING", name="notification_type"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
